server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/security
    driver-class-name: org.mariadb.jdbc.Driver
    username: cos
    password: cos1234

  mvc:
    view:
      prefix: /templates/
      suffix: .mustache

  jpa:
    hibernate:
      ddl-auto: create #create update none
    show-sql: true
    defer-datasource-initialization: true


  sql:
    init:
      mode: always

  security:
    oauth2:
      client:
        registration:
          google: # /oauth2/authorization/google ? ??? ???? ??.
            client-id: 853698725771-1nvkgl9j7sg9sj45h45nkbg90epplsmd.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile


          facebook: # /oauth2/authorization/facebook ? ??? ???? ??.
             client-id: 991838321683525
             client-secret: a2c8edc9ed7ce1f89c014ee36b0074db
             scope:
              - email
              - public_profile

          naver:
            client-id: owuDUYJ0HVHnD3uiMZnc
            client-secret: B9cxZnqp6j
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

          kakao:
            client-id: 264edb35a42e39dc36007baf5a6c82a7
            client-secret: AeCtboPpB54BoelVgjLF4xcrwMhCg68u
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email





        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response #?? ?? JSON?? response ???? ?

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id #kakao
