server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/security
    driver-class-name: org.mariadb.jdbc.Driver
    username: cos
    password: cos1234

  mvc:
    view:
      prefix: /templates/
      suffix: .mustache

  jpa:
    hibernate:
      ddl-auto: create #create update none
    show-sql: true
    defer-datasource-initialization: true


  sql:
    init:
      mode: always

  security:
    oauth2:
      client:
        registration:
          google: # /oauth2/authorization/google ? ??? ???? ??.
            client-id: 853698725771-1nvkgl9j7sg9sj45h45nkbg90epplsmd.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile


          facebook: # /oauth2/authorization/google ? ??? ???? ??.
             client-id: 991838321683525
             client-secret: a2c8edc9ed7ce1f89c014ee36b0074db
             scope:
              - email
              - public_profile
                
                
                
